export const ErrorCodes = {
	PAYMENT_METHOD_ALREADY_EXISTS: "PAYMENT_METHOD_ALREADY_EXISTS",
	PAYMENT_METHOD_NOT_FOUND: "PAYMENT_METHOD_NOT_FOUND",
	EXCEL_FILE_WORKSHEET_NOT_FOUND: "EXCEL_FILE_WORKSHEET_NOT_FOUND",
	EXCEL_FILE_INVALID_HEADERS: "EXCEL_FILE_INVALID_HEADERS",
	EXCEL_FILE_NO_VALID_PAYMENTS: "EXCEL_FILE_NO_VALID_PAYMENTS",
} as const;

export type ErrorCodes = keyof typeof ErrorCodes;
